/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "educnsmvhzhcysaajdqa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdWNuc212aHpoY3lzYWFqZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDc5NzgsImV4cCI6MjA5MDAyMzk3OH0.T-hPYfMCancWavrlVZZXhUqRZpXF584BQJMQw5e_u-k"